openapi: 3.1.0

info:
    title: Order Management API
    description: >
        Production-grade Order Management REST API.
        This API is resource-oriented, stateless, versioned,
        and designed with strict validation, security,
        and backward compatibility guarantees.
    version: 1.0.0

servers:
    - url: https://api.example.com
      description: Production
    - url: http://localhost:3000
      description: Local development

tags:
    - name: Orders
      description: Order lifecycle operations

security:
    - BearerAuth: []

paths:
    /api/v1/orders:
        post:
            tags: [Orders]
            summary: Create an order
            description: >
                Creates a new order for the authenticated user.
                Server-controlled fields such as userId, status,
                price, and timestamps are derived internally.
            operationId: createOrder
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateOrderRequest"
            responses:
                "201":
                    description: Order created successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OrderResponse"
                "400":
                    description: Validation error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "401":
                    description: Unauthenticated
                "403":
                    description: Forbidden

        get:
            tags: [Orders]
            summary: List orders
            description: >
                Returns a paginated list of orders belonging
                to the authenticated user. Uses cursor-based pagination.
            operationId: listOrders
            parameters:
                - $ref: "#/components/parameters/LimitParam"
                - $ref: "#/components/parameters/CursorParam"
                - $ref: "#/components/parameters/OrderStatusFilter"
            responses:
                "200":
                    description: Orders retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OrderListResponse"
                "400":
                    description: Invalid query parameters
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "401":
                    description: Unauthenticated
                "403":
                    description: Forbidden

    /api/v1/orders/{orderId}:
        get:
            tags: [Orders]
            summary: Get order by ID
            description: >
                Retrieves a single order by its identifier.
                Users may only access their own orders.
            operationId: getOrderById
            parameters:
                - $ref: "#/components/parameters/OrderIdParam"
            responses:
                "200":
                    description: Order retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OrderResponse"
                "404":
                    description: Order not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "401":
                    description: Unauthenticated
                "403":
                    description: Forbidden

    /api/v1/orders/{orderId}/cancel:
        post:
            tags: [Orders]
            summary: Cancel an order
            description: >
                Cancels an order if it is in a cancellable state.
                Cancellation rules are enforced by business logic.
            operationId: cancelOrder
            parameters:
                - $ref: "#/components/parameters/OrderIdParam"
            responses:
                "200":
                    description: Order cancelled successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OrderResponse"
                "409":
                    description: Order cannot be cancelled
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Order not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "401":
                    description: Unauthenticated
                "403":
                    description: Forbidden

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    parameters:
        OrderIdParam:
            name: orderId
            in: path
            required: true
            description: Unique identifier of the order
            schema:
                type: string

        LimitParam:
            name: limit
            in: query
            description: >
                Maximum number of orders to return.
                Hard upper limit enforced for system protection.
            schema:
                type: integer
                minimum: 1
                maximum: 50
                default: 20

        CursorParam:
            name: cursor
            in: query
            description: >
                Opaque cursor for pagination.
                Cursor always narrows results.
            schema:
                type: string

        OrderStatusFilter:
            name: status
            in: query
            description: Filter orders by status
            schema:
                type: string
                enum: [PENDING, CONFIRMED, CANCELLED]

    schemas:
        CreateOrderRequest:
            type: object
            additionalProperties: false
            required:
                - productId
                - quantity
            properties:
                productId:
                    type: string
                    description: Product identifier
                quantity:
                    type: integer
                    minimum: 1
                    maximum: 10
                    description: >
                        Number of units.
                        Business-enforced upper limit.

        Order:
            type: object
            required:
                - id
                - productId
                - quantity
                - status
                - createdAt
            properties:
                id:
                    type: string
                productId:
                    type: string
                quantity:
                    type: integer
                status:
                    type: string
                    enum: [PENDING, CONFIRMED, CANCELLED]
                createdAt:
                    type: string
                    format: date-time

        OrderResponse:
            type: object
            required: [data]
            properties:
                data:
                    $ref: "#/components/schemas/Order"

        OrderListResponse:
            type: object
            required: [data, meta]
            properties:
                data:
                    type: array
                    items:
                        $ref: "#/components/schemas/Order"
                meta:
                    type: object
                    properties:
                        nextCursor:
                            type: string
                            nullable: true

        ErrorResponse:
            type: object
            required: [error]
            properties:
                error:
                    type: object
                    required: [code, message]
                    properties:
                        code:
                            type: string
                            description: Machine-readable error code
                        message:
                            type: string
                            description: Human-readable error message
                        details:
                            type: object
                            additionalProperties: true
